
#============================================================
# Calculate node degree of perturbation (DP)
#
# DP = rewired edges / total adjacent edges
#
# Args:
#   rewired_edges : edge rewiring table generated by
#                   identify_module_rewiring()
#   gene_module   : gene-module assignment table generated by
#                   detect_modules()
#
# Returns:
#   Gene DP table
#============================================================

calculate_node_DP <- function(rewired_df,
                              gene_module){
  
  gene_dp <- gene_module
  colnames(gene_dp)[1] <- "gene"
  
  rewiring_cols <- grep("->", colnames(rewired_df))
  
  genes <- gene_dp$gene
  
  pb <- progress_bar$new(total = length(genes))
  
  for(g in genes){
    
    node_edge <- rewired_df[
      rewired_df$X1 == g |
        rewired_df$X2 == g,
    ]
    
    gene_dp[
      gene_dp$gene == g,
      colnames(rewired_df)[(rewiring_cols)]
    ] <-
      apply(
        node_edge[, rewiring_cols, drop = FALSE],
        2,
        function(x){
          sum(x == "inter") / length(x)
        }
      )
    pb$tick()
  }
  
  return(gene_dp)
}


#============================================================
# Calculate module degree of perturbation (DP)
#
# DP = rewired edges / total module-associated edges
#
# Args:
#   rewired_df  : edge rewiring table generated by
#                 identify_module_rewiring()
#   gene_module : gene-module assignment table generated by
#                 detect_modules()
#
# Returns:
#   Module DP table
#============================================================

calculate_module_DP <- function(rewired_df,
                                gene_module){
  
  colnames(rewired_df)[1:2] <- c("protein1", "protein2")
  
  rownames(gene_module) <- gene_module[,1]
  gene_module <- gene_module[,-1,drop=FALSE]
  
  rewiring_cols <- grep("->", colnames(rewired_df))
  
  module_dp <- c()
  
  ## 每个transition对应当前state的模块
  for(i in seq_along(rewiring_cols)){
    
    transition <- colnames(rewired_df)[rewiring_cols[i]]
    cat("Processing:",transition, "\n")
    
    modules <- sort(unique(gene_module[,i]))
    
    res <- data.frame(
      module = modules,
      nodeCount = NA_integer_,
      edgeCount = NA_integer_,
      interEdge = NA_integer_,
      DP = NA_real_
    )
    
    for(j in seq_along(modules)){
      
      module_gene <-
        rownames(gene_module)[
          gene_module[,i] == modules[j]
        ]
      
      ## 至少一个端点属于该模块
      edge <- rewired_df[
        rewired_df$protein1 %in% module_gene |
          rewired_df$protein2 %in% module_gene,
      ]
      
      res$transition[j] <- transition
      res$nodeCount[j] <- length(module_gene)
      res$edgeCount[j] <- nrow(edge)
      res$interEdge[j] <- sum(edge[[rewiring_cols[i]]] == "inter")
      res$DP[j] <- res$interEdge[j] / res$edgeCount[j]
    }
    
    module_dp <- rbind(module_dp,res)
  }
  
  return(module_dp)
}


