#============================================================
# Identify module rewiring between adjacent disease states
#
# Classify every interaction as:
#   intra : module relationship unchanged
#   inter : module relationship changed
#
# Args:
#   gene_module : gene-module assignment table generated by
#                 detect_modules()
#   network     : weighted PPI network generated by
#                 build_state_network()
#
# Returns:
#   A list of edge annotation tables.
#   Each element corresponds to one adjacent state pair.
#============================================================

identify_module_rewiring <- function(gene_module,
                                     network){
  
  ##----------------------------------------------------------
  ## prepare gene-module matrix
  ##----------------------------------------------------------
  
  rownames(gene_module) <- gene_module[,1]
  gene_module <- gene_module[, -1, drop = FALSE]
  
  edge_base <- network[, 1:2, drop = FALSE]
  
  rewired_edges_list <- list()
  rewired_res <- edge_base
    
  n_state <- ncol(gene_module)
  
  ##==========================================================
  ## loop over adjacent states
  ##==========================================================
  
  for(statei in seq_len(n_state - 1)){
    
    transit <- paste0(colnames(gene_module)[statei], 
                      "->", colnames(gene_module)[statei+1])
    cat("Processing state:", transit, "\n")
    
    module_s <- gene_module[, statei, drop=F]
    module_t <- gene_module[, statei + 1, drop=F]
    
    edge_df <- edge_base
    
    ##--------------------------------------------------------
    ## module assignment in two states
    ##--------------------------------------------------------
    
    edge_df$module1_s <- module_s[edge_df[,1],]
    edge_df$module2_s <- module_s[edge_df[,2],]
    
    edge_df$module1_t <- module_t[edge_df[,1],]
    edge_df$module2_t <- module_t[edge_df[,2],]
    
    ##--------------------------------------------------------
    ## current state edge type
    ##--------------------------------------------------------
    
    edge_df$currentType <- ifelse(
      edge_df$module1_s == edge_df$module2_s,
      "inner",
      "outer"
    )
    
    ##--------------------------------------------------------
    ## next state edge type
    ##--------------------------------------------------------
    
    edge_df$nextType <- ifelse(
      edge_df$module1_t == edge_df$module2_t,
      "inner",
      "outer"
    )
    
    ##--------------------------------------------------------
    ## rewiring classification
    ##--------------------------------------------------------
    
    edge_df$rewiringType <- ifelse(
      edge_df$currentType == edge_df$nextType,
      "intra",
      "inter"
    )
    
    edge_df$state <- statei
    
    rewired_edges_list[[statei]] <- edge_df
    
    rewired_res[[transit]] <- edge_df$rewiringType
  }
  
  return(list(
    rewired_edges_summary = rewired_res,
    rewired_edges_list = rewired_edges_list
  ))
}

calculate_node_DP <- function(rewired_df,
                              gene_module){
  
  gene_dp <- gene_module
  colnames(gene_dp)[1] <- "gene"
  
  rewiring_cols <- grep("->", colnames(rewired_df))
  
  genes <- gene_dp$gene
  
  pb <- progress_bar$new(total = length(genes))
  
  for(g in genes){
    
    node_edge <- rewired_df[
      rewired_df$X1 == g |
        rewired_df$X2 == g,
    ]
    
    gene_dp[
      gene_dp$gene == g,
      colnames(rewired_df)[(rewiring_cols)]
    ] <-
      apply(
        node_edge[, rewiring_cols, drop = FALSE],
        2,
        function(x){
          sum(x == "inter") / length(x)
        }
      )
    pb$tick()
  }
  
  return(gene_dp)
}

calculate_module_DP <- function(rewired_df,
                                gene_module){
  
  rownames(gene_module) <- gene_module[,1]
  gene_module <- gene_module[,-1,drop=FALSE]
  
  rewiring_cols <- grep("->", colnames(rewired_df))
  
  module_dp <- c()
  
  ## 每个transition对应当前state的模块
  for(i in seq_along(rewiring_cols)){
    
    transition <- colnames(rewired_df)[rewiring_cols[i]]
    cat("Processing:",transition, "\n")
    
    modules <- sort(unique(gene_module[,i]))
    
    res <- data.frame(
      module = modules,
      nodeCount = NA_integer_,
      edgeCount = NA_integer_,
      interEdge = NA_integer_,
      DP = NA_real_
    )
    
    for(j in seq_along(modules)){
      
      module_gene <-
        rownames(gene_module)[
          gene_module[,i] == modules[j]
        ]
      
      ## 至少一个端点属于该模块
      edge <- rewired_df[
        rewired_df$X1 %in% module_gene |
          rewired_df$X2 %in% module_gene,
      ]
      
      res$transition[j] <- transition
      res$nodeCount[j] <- length(module_gene)
      res$edgeCount[j] <- nrow(edge)
      res$interEdge[j] <- sum(edge[[rewiring_cols[i]]] == "inter")
      res$DP[j] <- res$interEdge[j] / res$edgeCount[j]
    }
    
    module_dp <- rbind(module_dp,res)
  }
  
  return(module_dp)
}


